TestProject/ViewModels/LoginModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TestProject.ViewModels
{
    public class LoginModel
    {
        [Required]
        public string Name { get; set; }
        [Required]
        [DataType(DataType.Password)]
        //[UIHint("password")]
        public string Password { get; set; }
        public string ReturnUrl { get; set; } = "/";
    }
}

TestProject/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TestProject.Data.ViewModels;

namespace TestProject.Controllers
{
    public class AccountController : Controller
    {
        private readonly SignInManager<IdentityUser> signInManager;

        public AccountController(SignInManager<IdentityUser> signInManager)
        {
            this.signInManager = signInManager;
        }
        public IActionResult Login(string returnUrl)
        {
            return View(new LoginModel { ReturnUrl = returnUrl });
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await signInManager.PasswordSignInAsync(model.Name, model.Password, false, false);
                if (result.Succeeded)
                {
                    if(!string.IsNullOrEmpty(model.ReturnUrl) && Url.IsLocalUrl(model.ReturnUrl))
                    {
                        return Redirect(model.ReturnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Error");
                }
            }
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

TestProject/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TestProject.Data.Interfaces;
using TestProject.Data.Models;

namespace TestProject.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly IAllCars allCars;

        public AdminController(IAllCars allCars)
        {
            this.allCars = allCars;
        }
        public IActionResult Index()
        {
            return View(allCars.Category);
        }
        public IActionResult EditCar(int id)
        {
            return View(allCars.Cars.FirstOrDefault(p => p.Id == id));
        }
        [HttpPost]
        public IActionResult EditCar(Car car)
        {
            if (ModelState.IsValid)
            {
                allCars.CreateCar(car);
                return RedirectToAction("Index");
            }
            return View(car);
        }
        [HttpPost]
        public IActionResult DeleteCar(int id)
        {
            allCars.DeleteCar(id);
            return RedirectToAction("Index");
        }
        public IActionResult CreateCar()
        {
            return View("EditCar", new Car());
        }
    }
}

TestProject/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TestProject.Data.Infrastructure;
using TestProject.Data.Interfaces;
using TestProject.Data.Models;

namespace TestProject.Controllers
{
    public class CartController : Controller
    {
        private readonly IAllCars allCars;
        private readonly Cart cart;

        public CartController(IAllCars allCars, Cart cart)
        {
            this.allCars = allCars;
            this.cart = cart;
        }
        public IActionResult CartIndex()
        {
            return View(cart);
        }
        public IActionResult AddItem(int id)
        {
            var car = allCars.Cars.FirstOrDefault(p => p.Id == id);
            if(car != null)
            {
                cart.AddItem(car, 1);
            }
            
            return RedirectToAction("CartIndex");
        }
        public IActionResult RemoveCart(int id)
        {
            cart.RemoveCart(id);
            return RedirectToAction("CartIndex");
        }
    }
}

TestProject/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TestProject.Data.Interfaces;

namespace TestProject.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IAllCars allCars;

        public CategoryController(IAllCars allCars)
        {
            this.allCars = allCars;
        }
        [Route("/Category/List")]
        [Route("/Category/List/{category}")]
        public IActionResult List(string category)
        {
            if (!string.IsNullOrEmpty(category))
            {
                if(string.Equals("electro", category))
                {
                    var cars = allCars.Category.Where(p => p.Category.Name.Equals("electro"));
                    return View(cars);
                }
                else if(string.Equals("fuil", category))
                {
                    var cars = allCars.Category.Where(p => p.Category.Name.Equals("fuil"));
                    return View(cars);
                }
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

TestProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TestProject.Data.Interfaces;

namespace TestProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAllCars allCars;

        public HomeController(IAllCars allCars)
        {
            this.allCars = allCars;
        }
        public IActionResult Index()
        {
            return View(allCars.Cars);
        }
        public IActionResult OneCar(int id)
        {
            var car = allCars.GetOneCar(id);
            return View(car);
        }
    }
}

TestProject/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TestProject.Data.Interfaces;
using TestProject.Data.Models;

namespace TestProject.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrders orderRep;
        private readonly Cart cart;

        public OrderController(IOrders orderRep, Cart cart)
        {
            this.orderRep = orderRep;
            this.cart = cart;
        }
        [Authorize]
        public IActionResult List()
        {
            return View(orderRep.GetAllOrders);
        }
        public IActionResult Checkout()
        {
            return View(new Order());
        }
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (ModelState.IsValid)
            {
                orderRep.SaveOrder(order);
                return RedirectToAction("Complete");
            }
            return View(order);
        }
        public IActionResult Complete()
        {
            cart.ClearCart();
            return View();
        }
        [HttpPost]
        public IActionResult DeleteOrder(int id)
        {
            orderRep.DeleteOrder(id);
            return RedirectToAction("List");
        }
    }
}

TestProject/Views/Admin/EditCar.cshtml
@model Car
@{
    ViewData["Title"] = "EditCar";
}

<h1>EditCar</h1>
<div class="container">
    <form method="post" asp-action="EditCar">
        <input type="hidden" asp-for="Id" />
        <div>
            <label asp-for="Name">@Model.Name</label>
            <div><span asp-validation-for="Name" class="text-danger"></span></div>
            <input asp-for="Name" />
        </div>
        <div>
            <label asp-for="Img1">@Model.Img1</label>
            <div><span asp-validation-for="Img1" class="text-danger"></span></div>
            <input asp-for="Img1" />
        </div>
        <div>
            <label asp-for="Price">@Model.Price</label>
            <div><span asp-validation-for="Price" class="text-danger"></span></div>
            <input asp-for="Price" />
        </div>
        <div>
            <label asp-for="Category.Name">Категория@*@Model.Category.Name*@</label>
            <div><span asp-validation-for="Category.Name" class="text-danger"></span></div>
            <input asp-for="Category.Name" />
        </div>
        <div>
            <input type="submit" value="Сохранить" class="btn btn-warning" />
            <a asp-action="Index" class="btn btn-danger">Отмена</a>
        </div>
    </form>
</div>

TestProject/Views/Admin/Edite.cshtml
@model Car
@{
    ViewData["Title"] = "Edite";
}

    <form asp-action="Edite" method="post">
        <div class="form-group">
            <input type="hidden" asp-for="@Model.Id" />
        </div>
        @*<div class="form-group">
            <img src="@Model.Img" width="100" />
            <div class="col-12">
                <input name="Img" value="@Model.Img" class="form-control"/>
                <span asp-validation-for="Img" class="text-danger"></span>
            </div>
        </div>*@
        <div class="form-group">
            <label asp-for="Img"></label>
            <div class="col-12">
                <input asp-for="Img" class="form-control" />
                <span asp-validation-for="Img" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Name"></label>
            <div class="col-12">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Price"></label>
            <div class="col-12">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <button type="submit" class="btn btn-danger">Save</button>
        <a asp-action="Index" class="btn btn-danger">Cancel</a>
    </form>

TestProject/Views/Admin/Index.cshtml
@model IEnumerable<Car>
@{
    ViewData["Title"] = "Index";
}


    <div class="container">
        <table class="table">
            <tr><th>Модель</th><th>Цена</th><th>Категория</th><th></th></tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Price</td>
                    <td>@item.Category.Name</td>
                    <td>
                        <form method="post" asp-action="DeleteCar">
                            <a asp-action="EditCar" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Редактировать</a>
                            <input type="hidden" name="Id" value="@item.Id" />
                            <input type="submit" value="Удалить" class="btn btn-danger btn-sm" />
                        </form>
                    </td>
                </tr>
            }
        </table>
        <div>
            <form method="post" asp-action="Logout" asp-controller="Account">
                <a asp-action="CreateCar" class="btn btn-warning btn-sm">Добавить автомобиль</a>
                <input type="submit" value="Выход" class="btn btn-danger btn-sm" />
            </form>
        </div>
    </div>

TestProject/Views/Cart/CartIndex.cshtml
@model Cart

@{
    ViewData["Title"] = "CartIndex";
}

<div class="container">
    <table class="table">
        <tr><th>Модель</th><th>Цена</th><th>Количество</th><th></th></tr>
        @foreach (var car in Model.Lines)
        {
            <tr>
                <td>@car.Car.Name</td>
                <td>@car.Car.Price.ToString("c")</td>
                <td>@car.Quantity</td>
                <td><a asp-action="RemoveCart" asp-controller="Cart" asp-route-id="@car.Id" class="btn btn-danger">Удалить</a></td>
            </tr>

        }
    </table>
    <a asp-action="Checkout" asp-controller="Order" class="btn btn-warning">Перейти к оплате</a>
</div>

TestProject/Views/Category/List.cshtml
@model IEnumerable<Car>
@{
    ViewData["Title"] = "List";
}

<div class="container">
    <div class="row">
        @foreach (var car in Model)
        {
            <div class="col-4">
                <img src="@car.Img1" class="img-thumbnail" />
                <h3>Модель: @car.Name</h3>
                <h4>Цена: @car.Price.ToString("c")</h4>
                <a asp-action="AddItem" asp-controller="Cart" asp-route-id="@car.Id" class="btn btn-warning">Добавить в корзину</a>
            </div>
        }
    </div>
</div>

TestProject/Views/Home/Index.cshtml
@model IEnumerable<Car>
@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <div class="row">
        @foreach(var car in Model)
        {
        <div class="col-4">
            <img src="@car.Img1" class="img-thumbnail" />
            <h3>Модель: @car.Name</h3>
            <h4>Цена: @car.Price.ToString("c")</h4>
            <div>
                <a asp-action="AddItem" asp-controller="Cart" asp-route-id="@car.Id" class="btn btn-warning btn-sm">Добавить в корзину</a>
                <a asp-action="OneCar" asp-controller="Home" asp-route-id="@car.Id" class="btn btn-warning btn-sm">Подробности</a>
            </div>
        </div>
        }
    </div>
</div>

TestProject/Views/Home/OneCar.cshtml
@model Car
@{
    ViewData["Title"] = "OneCar";
}

<h1 class="text-center">@Model.Name</h1>
<div class="container">
    <div class="row">
        <div class="col-8">
            <img src="@Model.Img1" class="img-thumbnail" />
        </div>
        <div class="col-4">
            <div><img src="@Model.Img2" class="img-thumbnail" /></div><br />
            <div><img src="@Model.Img3" class="img-thumbnail" /></div>
        </div>
    </div>
    <div class="row">
        <table class="table">
            <tr><th>Модель</th><td>@Model.Name</td></tr>
            <tr><th>Кузов</th><td>@Model.Body</td></tr>
            <tr><th>Привод</th><td>@Model.Drive</td></tr>
            <tr><th>Разгон до 100км/ч</th><td>@Model.Racing.ToString("f") сек</td></tr>
            <tr><th>Максимальная скорость</th><td>@Model.MaxSpeed км/ч</td></tr>
            <tr><th>Цена</th><td>@Model.Price.ToString("c")</td></tr>
            <tr><th></th><td></td></tr>
        </table>
    </div>
    <div><a asp-action="AddItem" asp-controller="Cart" asp-route-id="@Model.Id" class="btn btn-warning btn-sm">Добавить в корзину</a></div>
</div>

TestProject/Views/Order/Checkout.cshtml
@model Order
@{
    ViewData["Title"] = "Checkout";
}

<div class="container">
    <form method="post" asp-action="Checkout">
        <div class="form-group">
            <label asp-for="FirstName">Имя</label>
            <input asp-for="FirstName" />
        </div>
        <div class="form-group">
            <label asp-for="LastName">Фамилия</label>
            <input asp-for="LastName" />
        </div>
        <div class="form-group">
            <label asp-for="Email">Email</label>
            <input asp-for="Email" />
        </div>
        <div class="form-group">
            <input type="submit" value="Оплатить" class="btn btn-dark" />
        </div>
    </form>
</div>

TestProject/Views/Order/Complete.cshtml
@{
    ViewData["Title"] = "Complete";
}

    <div class="container">
        <h2>Покупка завершена!</h2>
    </div>

TestProject/Views/Order/List.cshtml
@model IEnumerable<Order>
@{
    ViewData["Title"] = "List";
}

<div class="container">
    <table class="table">
        <tr><th>Имя</th><th>Фамилия</th><th>Email</th><th colspan="4">Детали</th></tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.FirstName</td>
                <td>@item.LastName</td>
                <td>@item.Email</td>
                <td>Модель</td>
                <td>Цена</td>
                <td>Количество</td>
                <td>
                    <form method="post" asp-action="DeleteOrder">
                        <input type="hidden" value="@item.Id" name="Id"/>
                        <input type="submit" value="Удалить" class="btn btn-danger btn-sm"/>
                    </form>
                </td>
            </tr>
            @foreach(var car in item.OrderItems)
            {
                <tr>
                    <td colspan="3"></td>
                    <td>@car.Name</td>
                    <td>@car.Price</td>
                    <td>@car.Quantity</td>
                    <td></td>
                </tr>
            }
        }
    </table>
</div>

TestProject/Views/Order/OrderIndex.cshtml
@model Order
@{
    ViewData["Title"] = "OrderIndex";
}

<div class="container">
    <form asp-action="CreateOrder" method="post">
        <div class="form-group">
            <label asp-for="Name">Your name</label>
            <div>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Adress">Your adress</label>
            <div>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
        </div>
        <button type="submit" class="btn btn-danger">Finish Order</button>
    </form>
</div>

TestProject/Views/Order/OrderShow.cshtml
@model IEnumerable<Order>
@{
    ViewData["Title"] = "OrderShow";
}

<div class="container">
    @foreach(var order in Model)
    {
    <div class="row">
        <div class="col">
            <h3>Name: @order.Name</h3>
            <h3>Adress: @order.Adress</h3>
            @foreach(var el in order.OrderDetailes)
            {
                <h4>@el.Car.Name</h4>
                <h4>@el.Car.Price</h4>
                <h4>@el.Car.Id</h4>
            }
            <br /><br />
        </div>
    </div>
    }
</div>

TestProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <a class="navbar-brand" href="#">Carousel</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Все авто<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Category/List/electro">Электро</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Category/List/fuil">Бензиновые</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Cart/CartIndex">Корзина</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>
</body>
</html>